rango/urls.py
from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^about/$', views.about, name='about'),
                       url(r'^category/(?P<category_name_url>\w+)/$', views.category, name='category'),
                       url(r'^add_category/$', views.add_category, name='add_category'),
                       url(r'^(?P<category_name_url>\w+)/add_page/$', views.add_page, name='add_page'),
                       url(r'^register/$', views.register, name='register'),
                       url(r'^login/$', views.user_login, name='login'),
                       url(r'^logout/$', views.user_logout, name='logout'),
                       url(r'^restricted/', views.restricted, name='restricted'),
                       )

tango_with_djang_project/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tango_with_djang_project.views.home', name='home'),
    # url(r'^tango_with_djang_project/', include('tango_with_djang_project.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rango.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
         'serve',
         {'document_root': settings.MEDIA_ROOT}),)

tango_with_django_project/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tango_with_djang_project.views.home', name='home'),
    # url(r'^tango_with_djang_project/', include('tango_with_djang_project.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rango.urls',namespace='rango')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
         'serve',
         {'document_root': settings.MEDIA_ROOT}),)

rango/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User)

    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __unicode__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page,Category,UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Category

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=128, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

        return cleaned_data

    class Meta:
        model = Page
        fields = ('title', 'url', 'views')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

from utils import encode_url,decode_url

from rango.models import Category
from rango.models import Page

from rango.forms import CategoryForm
from rango.forms import PageForm
from rango.forms import UserForm, UserProfileForm


def index(request):
    context = RequestContext(request)

    category_list = Category.objects.order_by('-likes')[:5]
    pages_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories':category_list,
                    'pages':pages_list}

    for category in category_list:
        category.url = encode_url(category.name)

    return render_to_response('rango/index.html', context_dict, context)

def about(request):
    context = RequestContext(request)
    context_dict = {'message': 'Here is the about page'}
    return render_to_response('rango/about.html', context_dict, context)

def category(request, category_name_url):
    context = RequestContext(request)

    category_name = decode_url(category_name_url)
    context_dict = {'category_name':category_name,
                    'category_name_url':category_name_url}

    try:
        category = Category.objects.get(name=category_name)
        pages = Page.objects.filter(category=category)

        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        pass

    return render_to_response('rango/category.html', context_dict, context)

def add_category(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print form.errors
    else:
        form = CategoryForm()
    return render_to_response('rango/add_category.html',{'form':form}, context)

def add_page(request, category_name_url):
    context = RequestContext(request)

    category_name = decode_url(category_name_url)
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            page = form.save(commit=False)

            try:
                cat = Category.objects.get(name=category_name)
                page.category = cat
            except Category.DoesNotExist:
                print category_name
                return render_to_response('rango/add_category.html',{},context)

            page.views = 0
            page.save()

            print 'here'

            return category(request, category_name_url)
        else:
            print form.errors
    else:
        page = PageForm()
    return render_to_response('rango/add_page.html',{'category_name_url':category_name_url,'page':page},context)

def register(request):
    context = RequestContext(request)

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            print user.password
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['pictures']
            profile.save()

            registered = True
        else:
            print user_form.errors, profile_form.errors
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render_to_response(
        'rango/register.html',
        {'user_form':user_form, 'profile_form':profile_form, 'registered':registered},
        context)

def user_login(request):
    context = RequestContext(request)

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/rango/')
            else:
                return HttpResponse('Your Rango account is disabled.')
        else:
            return render_to_response('rango/login.html', {'error':'Invalid username or password.'}, context)
    else:
        return render_to_response('rango/login.html', {}, context)

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/rango/')

@login_required
def restricted(request):
    return HttpResponse("Since you're logged in, you can see this text!")

templates/rango/about.html
<!DOCTYPE html>

{% load static %}

<html>

  <body>
    <h1>Rango Says:</h1><p>{{ message }}</p>
    <img src="{% static "rango.jpg" %}" alt="rango picture" />
  </body>

</html>

templates/rango/add_category.html
<!DOCTYPE html>
<html>
  <head>
    <title>Rango</title>
  </head>

  <body>
    <h1>Add a Category</h1>

    <form id="category_form" method="post" action="/rango/add_category/">
      
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
      	{{ hidden }}
      {% endfor %}

      {% for field in form.visible_fields %}
      	{{ field.errors }}
        {{ field.help_text }}
        {{ field }}
      {% endfor %}

      <input type="submit" name="submit" value="Create Category" />
    </form>
  </body>
</html>

templates/rango/add_page.html
<!DOCTYPE html>
<html>
  <head>
    <title>Add a Page</title>
  </head>

  <body>
    <h1>Add a Page</h1>

    <form method="post" action="/rango/{{ category_name_url }}/add_page/">

      {% csrf_token %}
      {% for hidden in page.hidden_fields %}
        {{ hidden }}
      {% endfor %}

      {% for field in page.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}
      {% endfor %}

      <input type="submit" name="submit" value="Create Page" />
    </form>
  </body>
</html>

templates/rango/category.html
<!DOCTYPE html>
<html>
  <head>
    <title>Rango</title>
  </head>

  <body>
    <h1>{{ category_name }}</h1>
    {% if category %}

    {% if pages %}
    <ul>
      {% for page in pages %}
      <li><a href="{{ page.url }}">{{ page.title }}</a></li>
      {% endfor %}
    </ul>
    {% endif %}

    {% else %}
    <strong>No pages currently in category.</strong>
    The specified category {{ category_name }} does not exist!
    {% endif %}

    {% if user.is_authenticated %}
    <a href="/rango/{{ category_name_url }}/add_page/">Add a New Page</a>
    {% endif %}
  </body>
</html>

templates/rango/index.html
<!DOCTYPE html>
<html>

  <head>
    <title>Rango</title>
  </head>

  <body>
    {% if user.is_authenticated %}
    <h1>Rango says... hello {{ user.username }}!</h1>
    {% else %}
    <h1>Rango says...hello world!</h1>
    {% endif %}

    {% if categories %}
    <ul>
      {% for category in categories %}
      <li><a href="{% url 'rango:category' category.url %}">{{ category.name }}</a></li>
      {% endfor %}
    </ul>
    {% else %}
    <strong>There are no categories present.</strong>
    {% endif %}

    <h1>Top 5 pages</h1>

    {% if pages %}
    <ul>
      {% for page in pages %}
      <li><a href="{{ page.url }}">{{ page.title }}({{ page.views }})</a></li>
      {% endfor %}
    </ul>
    {% endif %}

    {% if user.is_authenticated %}
    <a href="/rango/add_category/">Add a New Category</a><br>
    <a href="/rango/restricted/">Restricted Page</a><br>
    <a href="/rango/logout/">Logout</a><br>
    {% else %}
    <a href="/rango/register/">Register Here</a><br>
    <a href="/rango/login/">Login</a><br />
    {% endif %}

    <a href="/rango/about/">About</a><br>
  </body>

</html>

templates/rango/login.html
<!DOCTYPE html>
<html>
  <head>
    <title>Rango</title>
  </head>

  <body>
    <h1>Login to Rango</h1>

    <form id="login_form" method="post" action="/rango/login/">
      {% csrf_token %}
      Username: <input type="text" name="username" value="" size="50" />
      <br />
      Password: <input type="password" name="password" value="" size="50" />
      <br />

      <input type="submit" value="submit" />
    </form>

    {% if error %}
    <p>{{ error }}</p>
    {% endif %}
  </body>
</html>

templates/rango/register.html
<!DOCTYPE html>
<html>
  <head>
    <title>Rango</title>
  </head>

  <body>
    <h1>Register with Rango</h1>

    {% if registered %}
    Rango says: <strong>thank you for registering!</strong>
    <a href="/rango/">Return to the homepage.</a><br />
    {% else %}
    Rango says: <strong>register here!</strong><br />

    <form id="user_form" method="post" action="/rango/register/" enctype="multipart/form-data">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}

      <input type="submit" name="submit" value="Register" />
    </form>
    {% endif %}
  </body>
</html>